spring.application.name=habittracker-api

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/habittracker_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Joserc2311_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080
server.address=0.0.0.0